# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/wenum-cli.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'wenum',
        'wenum.main',
        'wenum.core',
        'wenum.runtime_session',
        'wenum.fuzzobjects',
        'wenum.fuzzrequest',
        'wenum.fuzzqueues',
        'wenum.factories',
        'wenum.plugins',
        'wenum.plugin_api',
        'wenum.externals',
        'wenum.helpers',
        'wenum.ui',
        'linkfinder',
        'chardet',
        'pycurl',
        'pyparsing',
        'pySocks',
        'requests',
        'tomlkit',
        'beautifulsoup4',
        'python_dateutil',
        'pytz',
        'rich',
        'email',
        'email.message',
        'importlib.resources',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='wenum',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

